include:
  - notebooks-backend/compose.yaml
  - notes-backend/compose.yaml

services:
  reverse-proxy:
    image: nginx:1.27.0
    container_name: reverse-proxy
    volumes:
      - type: bind
        source: ./reverse-proxy/nginx.conf
        target: /etc/nginx/nginx.conf
    ports:
      - 5000:80
    networks:
      - notes-app-net
    depends_on:
      - notebooks
      - notes
  
networks:
  notes-app-net: